spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/requests/**
          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://10.148.0.2:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always